

services:
  web:
    build: .
    container_name: flask_app
    

    ports:
      - "5005:5000"
    volumes:
      
      - ./logs:/app/logs   # Mounts the logs directory for persistent logging


  
